name: ucode_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # di
  get_it: ^7.2.0
  dartz: ^0.10.1
  formz: ^0.4.1
  # state manager bloc
  flutter_bloc: ^8.1.1
  # equations
  equatable: ^2.0.5
  # cache hive
  hive: ^2.2.3
  path_provider: ^2.0.11
  # native splash
  flutter_native_splash: ^2.2.16
  # rest api
  dio: ^4.0.6
  # connection check
  connectivity_plus: ^3.0.2
  internet_connection_checker_plus: ^1.0.1
  # route
  go_router: ^6.0.0
  # keyboard dismiss on tap
  keyboard_dismisser: ^3.0.0
  # image network
  cached_network_image: ^3.2.3
  # box
  gap: ^2.0.1
  # firebase
  firebase_core: ^2.4.0
  firebase_analytics: ^10.0.8
  firebase_messaging: ^14.2.0
  firebase_crashlytics: ^3.0.8
  firebase_performance: ^0.9.0+8
  # local notification
  flutter_local_notifications: ^13.0.0
  # flow
  flow_builder: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
#  bloc_test: ^9.1.0
  hive_flutter: ^1.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/json/
    - assets/fonts/
    - assets/png/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
